### ISSUE TITLE
Sometimes forgets the project name 

### ISSUE THREAD

**Issue by chouvi** [gitbra/pwic#1]
Sometimes when you don't make an absolute reference, it forgets the project name and refers to the root path e.g. if the project name is myproj and I make a new page `mynew page` then instead of going to` http://localhost:8000/myproj/mynew page` it goes to `http://localhost:8000/mynew page `
example in articles `[link to new page](mynew%20page)`

thx

**Comment by gitbra** [comment]
Hello @chouvi. I finally reproduced your case and it is related to [this line](https://github.com/gitbra/pwic/blob/f5b38bb2b0c6e9a3407277b536f7280e0f67cac4/templates/js/page-edit.js#L50). The app considers the space character as a sign that the link is not relative, then it does not prepend the name of the project to build the link.

I need more time to qualify why this is written like that. Your question also raised another idea of improvement. I will have a look at both.

**Comment by chouvi** [comment]
Hello @gitbra. Thank you for your prompt reply. I noticed that this happens when you have a single project and click on the project name line above home. Then it loses the project name in the url since it redirects to the single project and not to a project selection menu. he goes to   `http://localhost:8000/myproj)` instead of the `http://localhost:8000/myproj/home)` with a base that works normally.
It would also be particularly useful to be able to drag and drop to select files since you can't drag and drop files from a tablet or mobile phone.
And one last question is there a way to preview docx files (e.g. using the viewer of google doc or office 365 or a plugin in the browser).
And by the way, congratulations for pwic it is excellent and  and easy to use. 

thx

**Comment by gitbra** [comment]
Hello @chouvi

A correction is available in f0e189e8698e64dd56208b2be1c9475bface9b5d among other changes. The project selection is not available when the user has access to one project only ([here](https://github.com/gitbra/pwic/blob/f0e189e8698e64dd56208b2be1c9475bface9b5d/pwic.py#L885)), then he is redirected to /project because the handler of the default page name is coded elsewhere ([here](https://github.com/gitbra/pwic/blob/f0e189e8698e64dd56208b2be1c9475bface9b5d/pwic.py#L740)). The homepage is an optional element of the location by design.

For the drag and drop, this could be implemented in a near future to cover your valid scenario.

I am not sure to understand what you mean by *previewing DOCX*. The purpose of the application is to render pages with the Markdown syntax only. If you want to import an Office document, you can use ODT but not DOCX. To convert from DOCX to MD, you can investigate Pandoc. Adding DOCX is a pending idea but also a lot of work.

Thanks for your kind words too.

**Comment by gitbra** [comment]
Hello @chouvi

The mobile upload of documents is added in 6e071638675d3dc67b3eb7176f7684db282e4bc6.
It should work as expected to fulfill your requirement.

Thanks to have brought new ideas.

**Comment by chouvi** [comment]
Hello @gitbra 
Great news, congratulations, Very good implementation of the mobile upload!!!
